# Configuration for H100 80GB PCIe

data:
  urls:
    - "http://images.cocodataset.org/zips/train2017.zip"
    - "http://images.cocodataset.org/zips/val2017.zip"
    - "http://images.cocodataset.org/zips/test2017.zip"

  raw_dir: "data/raw"
  extracted_dir: "data/coco"
  image_size: 256
  rotations: [0, 90, 180, 270]
  train_split: "train2017"
  val_split: "val2017"
  test_split: "test2017"

model:
  name: "mobilenetv4_conv_small"
  pretrained: true
  num_classes: 4
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

training:
  output_dir: "checkpoints"
  logs_dir: "logs"

  batch_size: 1024  # Balanced for H100 80GB
  epochs: 10
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  gradient_accumulation_steps: 1

  patience: 3
  num_workers: 16
  pin_memory: true
  prefetch_factor: 2
  keep_n_checkpoints: 3
  channels_last: true
  compile: true

export:
  coreml:
    enabled: true
    target_ios: 17
    fp16: true

  onnx:
    enabled: false
    opset_version: 17

logging:
  logs_dir: "logs"
