# Configuration for H100 80GB PCIe

data:
  urls:
    - "http://images.cocodataset.org/zips/train2017.zip"
    - "http://images.cocodataset.org/zips/val2017.zip"
    - "http://images.cocodataset.org/zips/test2017.zip"

  raw_dir: "data/raw"
  extracted_dir: "data/coco"
  image_size: 256
  train_split: "train2017"
  val_split: "val2017"
  test_split: "test2017"

  max_train_images: null  # Use all available images
  max_val_images: null

model:
  name: "mobilenetv4_conv_small"
  pretrained: true
  num_classes: 4
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

training:
  output_dir: "checkpoints"
  logs_dir: "logs"

  batch_size: 2048  # Large batch for 80GB H100
  epochs: 10
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4

  patience: 3
  num_workers: 8
  pin_memory: true
  prefetch_factor: 2

export:
  coreml:
    enabled: true
    quantization: "int8"  # Options: "int8", "fp16", "none"

  onnx:
    enabled: false
    opset_version: 17

logging:
  logs_dir: "logs"
